default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: subscription_api_development

test:
  <<: *default
  database: subscription_api_development_test

production:
  <<: *default
  database: subscription_api_development_production
  username: subscription_api_development
  password: <%= ENV['SUBSCRIPTION_API_DEVELOPMENT_DATABASE_PASSWORD'] %>
