# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
common: &common
  credentials:
    user: super
    password: duper
  billing_gateway:
    host: http://localhost:4567
    token: Basic YmlsbGluZzpnYXRld2F5

development:
  secret_key_base: f2d10f27ec227b6638eff0423640499c3b1a459268895d3eb452a09c86b95d34632fe7ed4c615d3f63bf0ff048f3691e9dab76ff170cbb52fb5e1de898221992
  <<: *common

test:
  secret_key_base: 85ff11af8123a93ea31877fd6245cfcbb057be8ef61a24edbbb1b8c9a265d661093c7291fde17931a1bdc144e1834b64ab6ac3b1b98ea4cfa92cae509e065f95
  <<: *common
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
